# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

api = "0.11"

[buildpack]
id = "xidletime"
version = "0.0.0"
description = "Measure the idle time of the XServer and expose it via a metrics endpoint."

[[targets]]
os = "linux"
