# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

api = "0.11"

[extension]
id = "capella-deps"
name = "Capella System dependencies (Xvfb, xauth, dbus-x11)"
version = "0.0.0"
