#!/bin/sh
# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

# Autostart script for OpenBox

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

command="/opt/eclipse/eclipse -consoleLog -data ${WORKSPACE_DIR:-/workspace}"
stdout="/var/log/session/eclipse.stdout.log"
stderr="/var/log/session/eclipse.stderr.log"

if [ "$AUTOSTART_ECLIPSE" = "1" ];
then
    if [ "$RESTART_ECLIPSE" = "1" ];
    then
        # Restart Eclipse automatically
        ( while true; do $command > $stdout 2> $stderr; sleep 1; done ) &
    else
        $command > $stdout 2> $stderr &
    fi
fi
