# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

import contextlib
import enum
import logging
import pathlib
import shutil
import subprocess

import typer
from rich import progress

log = logging.getLogger(__name__)


class SupportedArchitecture(str, enum.Enum):
    amd64 = "amd64"
    arm64 = "arm64"


def check_prerequisites():
    if not shutil.which("docker"):
        raise RuntimeError("Docker is required to run the CLI.")


def build_image_name(image_prefix: str, image_name: str, image_tag: str):
    image_prefix = image_prefix.removesuffix("/")
    if image_prefix:
        return f"{image_prefix}/{image_name}:{image_tag}"
    return f"{image_name}:{image_tag}"


@contextlib.contextmanager
def build_dockerignore(context: str, dockerignore: list[str]):
    content = [
        "# Do not edit this file!",
        "# It's auto-generated during the build process and will be deleted after the build.",
        "",
        *dockerignore,
    ]
    file = pathlib.Path(f"{context}/.dockerignore")

    with file.open("w", encoding="utf-8") as f:
        for line in content:
            f.write(f"{line}\n")

    try:
        yield
    finally:
        file.unlink()


def build_image(
    *,
    image_name: str,
    build_context: str,
    build_architecture: SupportedArchitecture,
    no_cache: bool,
    build_args: list[tuple[str, str]] | None = None,
):
    log.info("Start building Docker image '%s'...", image_name)
    with progress.Progress(
        progress.SpinnerColumn(style="yellow"),
        progress.TextColumn("       [progress.description]{task.description}"),
        transient=True,
    ) as spinner:
        spinner.add_task(
            f"[yellow]Building Docker image '{image_name}'[/yellow]"
        )
        cmd = ["build", build_context]
        if not build_args:
            build_args = []
        for key, value in build_args:
            cmd.extend(["--build-arg", f"{key}={value}"])
        cmd.extend(["-t", image_name])
        cmd.extend(["--platform", f"linux/{build_architecture.value}"])
        if no_cache:
            cmd.append("--no-cache")
        run_docker_subprocess(cmd)
    log.info("Successfully built Docker image '%s'", image_name)


def push_image(
    image_name: str,
):
    log.info("Start pushing Docker image '%s'...", image_name)
    with progress.Progress(
        progress.SpinnerColumn(style="yellow"),
        progress.TextColumn("       [progress.description]{task.description}"),
        transient=True,
    ) as spinner:
        spinner.add_task(
            f"[yellow]Pushing Docker image '{image_name}'[/yellow]"
        )

        run_docker_subprocess(["push", image_name])
    log.info("Successfully pushed Docker image '%s'", image_name)


def run_docker_subprocess(cmd: list[str]):
    full_cmd = ["docker", *cmd]
    log.debug("Running Docker command: '%s'", " ".join(full_cmd))
    process = subprocess.Popen(
        full_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT
    )
    stdout = ""
    if process.stdout:
        for line in iter(process.stdout.readline, b""):
            decoded_line = line.decode("utf-8")
            stdout += decoded_line
            log.debug(decoded_line.strip("\n"))
    exit_code = process.wait()
    if exit_code != 0:
        if logging.getLogger().level != logging.DEBUG:
            log.info(stdout)
        log.error("Docker command failed with exit code %d", exit_code)
        raise typer.Exit(exit_code)
