# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

api = "0.11"

[buildpack]
id = "xrdp"
version = "0.0.0"
description = "Install xrdp to expose X11 applications via RDP."

[[targets]]
os = "linux"
