#!/bin/bash
# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

# Autostart script
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export GTK_OVERLAY_SCROLLING=0

# Load environment variables from /etc/environment
source /etc/environment

# Turn off bell sound (loud beep)
xset b off

command="/opt/capella/capella -consoleLog -data ${WORKSPACE_DIR:-/workspace}"
stdout="/var/log/session/capella.stdout.log"
stderr="/var/log/session/capella.stderr.log"

if [ "$AUTOSTART_CAPELLA" = "1" ];
then
    if [ "$RESTART_CAPELLA" = "1" ];
    then
        # Run capella in a loop:
        ( while true; do $command > $stdout 2> $stderr; sleep 1; done ) &
    else
        $command > $stdout 2> $stderr &
    fi
fi
