#!/bin/sh
# Autostart script for OpenBox

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

nitrogen --restore &

if [ "$AUTOSTART_CAPELLA" = "1" ];
then
    # Run capella in a loop:
    ( while true; do /opt/capella/capella -data /workspace; sleep 1; done ) &
fi
