# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

api = "0.11"

[extension]
id = "xidletime-deps"
name = "Xidletime system dependencies"
version = "0.0.0"
