# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

site_name: MBSE Docker images
theme:
  name: material
  font: false
  palette:
    scheme: slate
    primary: indigo
    accent: light blue
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.sections
  icon:
    admonition:
      commercial: fontawesome/solid/dollar-sign

nav:
  - Introduction: index.md
  - Base:
      - Capella: base/capella/index.md
      - Papyrus: base/papyrus/index.md
      - Eclipse: base/eclipse/index.md
      - Jupyter: base/jupyter/index.md
  - Extensions:
      - TeamForCapella: extensions/t4c.md
      - 'pure::variants': extensions/pure-variants.md
      - Remote: extensions/remote.md
  - Hints:
      - Memory Options for JVM: hints/memory-options.md
      - Git hooks (pre-commit): hints/git-hooks/index.md
  - CI/CD templates:
      - Index: ci-templates/index.md
      - Gitlab:
          - Diagram cache: ci-templates/gitlab/diagram-cache.md
          - Release train: ci-templates/gitlab/release-train.md
          - Image builder: ci-templates/gitlab/image-builder.md
          - Model validation: ci-templates/gitlab/model-validation.md
          - T4C export: ci-templates/gitlab/t4c-export.md
          - Test container clean up: ci-templates/gitlab/cleanup.md
      - Github:
          - Diagram cache: ci-templates/github/diagram-cache.md
  - Development:
      - Testing: development/testing.md
      - Buildpacks: development/buildpacks.md

repo_url: https://github.com/DSD-DBS/capella-dockerimages
edit_uri: edit/master/docs/docs

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra:
  generator: false

extra_css:
  - stylesheets/commercial.css

copyright: Copyright &copy; 2022-2024 DB InfraGO AG
