# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

site_name: MBSE Docker images
theme:
  name: material
  font: false
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
    - content.code.annotate
nav:
  - Introduction: index.md
  - Base: base.md
  - Git hooks (pre-commit): git-hooks/git-hooks.md
  - CI/CD templates:
      - Index: ci-templates/index.md
      - Gitlab:
          - Diagram cache: ci-templates/gitlab/diagram-cache.md
          - Release train: ci-templates/gitlab/release-train.md
          - Image builder: ci-templates/gitlab/image-builder.md
          - Model validation: ci-templates/gitlab/model-validation.md
          - T4C export: ci-templates/gitlab/t4c-export.md
          - Test container clean up: ci-templates/gitlab/cleanup.md
      - Github:
          - Diagram cache: ci-templates/github/diagram-cache.md
  - Jupyter Notebooks: jupyter/index.md
  - Capella:
      - Introduction: capella/introduction.md
      - Base: capella/base.md
      - Remote: remote.md
      - Provisioning: capella/provisioning.md
      - 'pure::variants': pure-variants.md
      - Build from source: capella/build-from-source.md
      - Team4Capella client:
          - Introduction: capella/t4c/introduction.md
          - Base: capella/t4c/base.md
          - Exporter: capella/t4c/exporter.md
          - Importer: capella/t4c/importer.md
          - Remote: remote.md
  - Papyrus:
      - Base: papyrus/base.md
  - Eclipse:
      - Base: eclipse/base.md
      - Memory Options: eclipse/memory-options.md
      - 'pure::variants': pure-variants.md
  - Remote: remote.md
  - Development:
      - Testing: development/testing.md

repo_url: https://github.com/DSD-DBS/capella-dockerimages
edit_uri: edit/master/docs/docs

hooks:
  - copyright_hook.py

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra:
  generator: false
